#ifndef __GLOBAL_ENUMS
#define __GLOBAL_ENUMS

enum LevelSegment
{
	LEVEL_SEGMENT_BLANK = 0,
	LEVEL_SEGMENT_WALL,
	LEVEL_SEGMENT_PLAYER_FOOD,
	LEVEL_SEGMENT_PLAYER_SNAKE,
	LEVEL_SEGMENT_PLAYER_SNAKE_HEAD
};

#endif